/**
 * Public exports for the expr module.
 */

export {
	type AggExpr,
	type AliasExpr,
	type ArithmeticExpr,
	type BetweenExpr,
	type CaseConversionExpr,
	type ColumnExpr,
	type ComparisonExpr,
		type DateAddExpr,
	type CountDistinctExpr,
	type CountExpr,
		type DateParseExpr,
	type DateExtractExpr,
		type DiffDaysExpr,
		type TruncateDateExpr,
	type Expr,
	ExprType,
	formatExpr,
	isAggExpr,
	isArithmeticExpr,
	isColumnExpr,
	isComparisonExpr,
	type IsInExpr,
	isLiteralExpr,
	type LiteralExpr,
	type LogicalExpr,
	type NegExpr,
	type NotExpr,
	type NullCheckExpr,
	type PowExpr,
		type FormatDateExpr,
		type ParseJsonExpr,
	type ReplaceExpr,
	type RoundExpr,
	type StringLengthExpr,
	type StringOpExpr,
	type SubstringExpr,
	type TrimExpr,
	type UnaryMathExpr,
	type WhenClause,
	type WhenExpr,
} from "./ast.ts";

export {
	add,
	and,
	avg,
	between,
	coalesce,
	ColumnRef,
	col,
	parseJson,
	count,
	countDistinct,
	div,
	formatDate,
	addDays,
	subDays,
	diffDays,
	truncateDate,
	toDate,
	toTimestamp,
	first,
	last,
	lit,
	max,
	median,
	min,
	mod,
	mul,
	neg,
	not,
	or,
	std,
	sub,
	sum,
	typedLit,
	variance,
	when,
	WhenBuilder,
} from "./builders.ts";
export {
	applyPredicate,
	applyValue,
	type CompiledPredicate,
	type CompiledValue,
	compilePredicate,
	compileValue,
	countMatching,
} from "./compiler.ts";
export {
	type InferredType,
	inferExprType,
	isPredicateExpr,
	validateExpr,
} from "./types.ts";
